export const SEARCH_CITY_START = 'SEARCH_CITY_START';
export const SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS';
export const SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL';

export const SEARCH_COORDS_START = 'SEARCH_COORDS_START';
export const SEARCH_COORDS_SUCCESS = 'SEARCH_COORDS_SUCCESS';
export const SEARCH_COORDS_FAIL = 'SEARCH_COORDS_FAIL';
